<?xml version="1.0" encoding="utf-8"?><Database Name="perpus" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-TLSL6QM;Initial Catalog=perpus;User ID=sa" SettingsObjectName="perpus.Properties.Settings" SettingsPropertyName="perpusConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.employee" Member="employees">
    <Type Name="employee">
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="role" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.member" Member="members">
    <Type Name="member">
      <Column Name="nis" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nama" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="handphone" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="joindate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.book" Member="books">
    <Type Name="book">
      <Column Name="book_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="book_title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="book_type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="books_on_the_rack" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="books_borrowed" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="total_books" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.type" Member="types">
    <Type Name="type">
      <Column Name="type_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="type_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>